flake.lock
flake.nix
src/Cargo.lock

Having a nix flake makes it easy to develop on NixOS :)

added nix flake

---

src/File.roc
src/InternalFile.roc

The changes in #7 caused  the compiler to panic on `roc build file-test.roc`. I failed to get a partial revert to work.

revert PR #7

---

.github/workflows/ci.yml
examples/env.roc
src/File.roc
src/InternalFile.roc

Also fixed pf path in examples/env.roc
PR #16 should be merged first

More build tests

---

.github/workflows/ci.yml
ci/expect_scripts/args.exp
ci/expect_scripts/countdown.exp
ci/expect_scripts/echo.exp
ci/expect_scripts/env.exp
ci/expect_scripts/file-read.exp
ci/expect_scripts/form.exp
ci/expect_scripts/http-get.exp
examples/.gitignore
examples/file-mixedBROKEN.roc
examples/file-read.roc
src/Cargo.lock
src/Cargo.toml
src/EnvDecoding.roc

also updated roc_std and fixed the CI script

fixed #25, added extra test

---

src/host.c

Fix bad exit code

---

examples/echo.roc
examples/record-builder.roc
src/Task.roc

https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Task.20return.20types/near/365002936

use * instead of [] for error type

---

examples/args.roc
examples/echo.roc
examples/env.roc
examples/file-mixedBROKEN.roc
examples/file-read.roc
examples/form.roc
examples/http-get.roc
examples/record-builder.roc
examples/tcp-client.roc
file-testBROKEN.roc
src/host.c
src/main.roc

Change main to `Task {} U32`

---

examples/.gitignore
examples/command.roc
src/Command.roc
src/Effect.roc
src/InternalCommand.roc
src/main.roc
src/src/command_glue.rs
src/src/file_glue.rs
src/src/lib.rs

Goals for this PR as described in [zulip thread](https://roc.zulipchat.com/#narrow/stream/316715-contributing/topic/running.20processes.20in.20basic-cli/near/366163748).
> I was just writing a shell script that basically executes some other programs and does things like:
> - checking their exit codes
> - capturing stdout and stderr
> - setting env vars for them

Add Command module

---

.github/workflows/ci.yml
ci/expect_scripts/command.exp
examples/command.roc

I also replaced ls with stat because that's easier for testing

add test for command example

---

examples/.gitignore
src/Effect.roc
src/Process.roc
src/src/lib.rs

Follow up from #65 to update `Process.exit` to also use `I32`

Update Process.exit to I32

---

src/Tty.roc

https://github.com/roc-lang/basic-cli/issues/73

mention planned move Ttty.roc

---

ci/expect_scripts/helloWorld.exp
examples/helloWorld.roc

Added helloWorld.roc + expect test

---

src/src/lib.rs

Removed roc_memcpy

---

README.md

added 0.3.2 docs, improve README

---

README.md

added 0.4.0 docs site

---

ci/expect_scripts/dir.exp
examples/.gitignore
examples/dir.roc
src/Dir.roc
src/Effect.roc
src/InternalDir.roc
src/src/dir_glue.rs
src/src/lib.rs

This PR 
- Adds `Dir.make`
- Adds `Dir.makeRecursive`
- Implements `Dir.deleteEmptyDir`
- Implements `Dir.deleteRecursive`
- Adds a CI test for the Dir module
- Simplifies error handling into a single IOError type to align closer to Rust [std::io::ErrorKind](https://doc.rust-lang.org/std/io/enum.ErrorKind.html)

Add new Dir features

---

src/Cargo.toml

Fix to the issues listed here: https://github.com/roc-lang/roc/pull/5882

Force exact reqwest version

---

.github/workflows/test_latest_release.yml
ci/all_tests.sh
ci/get_latest_release_examples.sh
ci/test_latest_release.sh

We were previously using the examples on latest main in combination with the platform of the latest release.

use examples of latest release for test_latest_release.yml

---

.github/workflows/ci_nix.yml
src/Cargo.toml

reqwest 0.11.22 was causing undefined symbols errors on macos

lower reqwest version

---

examples/dir.roc
src/src/lib.rs

This PR
- Implements `Dir.list`

Add `Dir.list` effect

---

src/src/lib.rs

Please cut a release after adding this. Should be safe to add before any of the roc compiler changes land.

add roc_dbg

---

src/src/lib.rs

Would be nice to make a minor release with this at some point.

add source location to dbg messages

---

.github/workflows/test_latest_release.yml
ci/expect_scripts/task-list.exp
examples/.gitignore
examples/task-list.roc
examples/tcp-client.roc
platform/Task.roc

See [zulip discussion](https://roc.zulipchat.com/#narrow/stream/304902-show-and-tell/topic/article.20about.20looping.20in.20Roc/near/412638345)

Add seq and Task.forEach

---

examples/hello-world.roc
flake.lock

normal hello world, flake lock update

---

CONTRIBUTING.md
ci/all_tests.sh
flake.lock

I believe these went undetected but now we can see them due to https://github.com/roc-lang/roc/pull/6842.
I also updated the flake.

Fix roc dev failures

---

examples/args.roc
platform/Arg/Cli.roc

weaver updates

---

.github/workflows/ci.yml
build.roc
flake.lock

Also test building for musl in CI and nix flake update to get the latest Roc commit.

build.roc musl support

---

.github/workflows/ci.yml
ci/all_tests.sh

It's nice to be able to disable these steps

Add NO_BUILD env var

---

build.roc

We forgot to update the `build.roc` script to v0.15, so it is currently trying and failing to build dynamically. This sets it to the latest version.

Pin build.roc platform to v0.15

---

.github/workflows/ci.yml
README.md
ci/all_tests.sh
flake.lock

This behavior is now enabled by default, the flag got removed in https://github.com/roc-lang/roc/pull/6859

remove --prebuilt-platform

---

Cargo.toml
crates/roc_host/src/lib.rs
examples/stdin.roc
platform/File.roc
platform/Path.roc
platform/Stdin.roc

Fix undefined symbol stdin read

---

platform/Dir.roc
platform/File.roc
platform/InternalPath.roc
platform/Path.roc

I ran into these while working on docs generation. Quick fixes!

Fix some documentation

---

examples/stdin.roc
platform/Http.roc
platform/InternalDateTime.roc
platform/Sqlite.roc
platform/Url.roc

Use new `and/or` keywords preferred by formatter

---

examples/countdown.roc

PNC-ify one stray WSA

---

ci/all_tests.sh
ci/expect_scripts/sqlite-everything.exp
examples/.gitignore
examples/sqlite-basic.roc
examples/sqlite-everything.roc

This examples also tests some previously untested functions.

more expansive sqlite example

---

tests/utc.roc

snake case, removed redundant comments

Utc cleanup

---

.gitignore
ci/all_tests.sh
ci/check_cargo_versions_match.roc
ci/expect_scripts/env.exp
ci/expect_scripts/tcp-client.exp
ci/expect_scripts/tcp.exp
ci/expect_scripts/url.exp
ci/expect_scripts/utc.exp
ci/rust_http_server/Cargo.lock
ci/rust_http_server/Cargo.toml
ci/rust_http_server/src/main.rs
tests/env.roc
tests/tcp.roc
tests/url.roc
tests/utc.roc

CI was taking a long time to run, these changes bring some massive speedups :tada:

speedup + xtra CI script

---

ci/expect_scripts/file.exp
crates/roc_file/src/lib.rs
crates/roc_host/src/lib.rs
platform/File.roc
platform/Host.roc
tests/file.roc

added File.rename!

---

ci/rust_http_server/src/main.rs
examples/http.roc

Avoids issues when using the test server with basic-webserver.

change test server port
