roc-lang/basic-cli

.gitignore
file-test.roc
src/Cargo.lock
src/Cargo.toml
src/File.roc
src/src/lib.rs

Added error handling for file reads and writes, and a roc app to test this. Note roc app likely only works on MacOS as it depends on hardcoded folders/files being present to trigger specific errors. 
```
luke@192-168-1-108 basic-cli % roc run file-test.roc                                  
🔨 Rebuilding platform...
Pass: expected NotFound
Pass: expected PermissionDenied
Pass: expected NotFound
Pass: expected PermissionDenied
Tests complete
```

added File Read/Write error handling

---

src/File.roc
src/InternalFile.roc

Based on how closed tag union types now work, we can now condense the error types for I/O operations down to a single type alias!
I'll leave this open until after Advent of Code is over, so as to avoid publishing any breaking changes while people are using it. 😄

Smaller error types

---

src/Tcp.roc

Exposing  `Tcp` error types so that the user can write `Task` annotations.

Expose error types from Tcp module

---

ci/expect_scripts/record-builer.exp
examples/.gitignore
examples/record-builder.roc
src/Task.roc

This PR adds `Task.batch` to enable applicative style use of Tasks.
Also relevant [zulip discusion](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Task.20apply/near/365000245)

Add `Task.batch` and example

---

examples/stdin.roc
src/Cargo.lock
src/Cargo.toml
src/Effect.roc
src/Stdin.roc
src/Tty.roc
src/main.roc
src/src/lib.rs

This PR;
1. Cross-platform support for entering terminal raw mode using the [crossterm](https://github.com/crossterm-rs/crossterm) library, and 
2. Changes `Stdin.byte` to `Stdin.bytes` to read in up to 256 bytes from the input buffer as this is a much more useful function than processing a single byte at a time.

Upgrade Stdin from `byte` to `bytes` add support for terminal raw mode

---

src/Task.roc

for now you can't use Task.succeed inside Task.roc when Task is exposed by the platform

import error workaround

---

examples/args.roc
examples/command.roc
examples/echo.roc
examples/env.roc
examples/file-mixedBROKEN.roc
examples/file-read.roc
examples/form.roc
examples/http-get.roc
examples/record-builder.roc
examples/stdin.roc
examples/tcp-client.roc
file-testBROKEN.roc
src/host.c
src/main.roc

This PR was discussed in this [zulip thread](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Basic-cli.20main.20failure.20type/near/368480397), and updates main from `main : Task {} U32` to `main : Task {} I32` so that negative integer values can be returned by Roc apps.

Modify main return from U32 to I32

---

examples/countdown.roc
examples/http-get.roc
examples/record-builder.roc
examples/stdin.roc
src/File.roc
src/InternalTask.roc
src/Task.roc
src/Tcp.roc

This PR updates Task to unify the API with Result. This change was discussed in [zulip thread](https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/Task.20and.20Result.20onErr/near/368724849).
- `Task.succeed` -> `Task.ok`
- `Task.fail` -> `Task.err`
- `Task.mapFail` -> `Task.mapErr`
- `Task.onFail` -> `Task.onErr`

Update Task module with `Task.ok` and `Task.err` to unify with Result API 

---

src/src/lib.rs

Fixes [this issue](https://github.com/roc-lang/basic-cli/issues/69)

Disable raw mode on panic

---

flake.nix
src/Task.roc

This error only happens in some cases, not sure why:
```
❯ ./target/release/roc examples/helloWorld.roc 
Downloading https://github.com/roc-lang/basic-cli/releases/download/0.4.0-rc1/XLXhHBQi4g0rf22b7NCFMTZGBDgvdibf_JdaipvMnNg.tar.br
into /home/username/.cache/roc/packages
── MODULE NOT IMPORTED ─ ...XhHBQi4g0rf22b7NCFMTZGBDgvdibf_JdaipvMnNg/Task.roc ─
The `Task` module is not imported:
127│                  Err b -> Task.err b |> InternalTask.toEffect
^^^^^^^^
Did you mean to import it?
── MODULE NOT IMPORTED ─ ...XhHBQi4g0rf22b7NCFMTZGBDgvdibf_JdaipvMnNg/Task.roc ─
The `Task` module is not imported:
144│                  Ok a -> Task.ok a |> InternalTask.toEffect
^^^^^^^
Did you mean to import it?
── MODULE NOT IMPORTED ─ ...XhHBQi4g0rf22b7NCFMTZGBDgvdibf_JdaipvMnNg/Task.roc ─
The …
```

workaround MODULE NOT IMPORTED error

---

src/src/lib.rs

It was failing due to GC collecting functions we want to expose to the linker.
@Anton-4, this should fix the musl build while still enable a small binary with garbage collection. I guess in a static build, garbage collection is more aggressive because it assumes that functions can't be exposed to dynamic libraries. So we have to explicitly protect them.
When we eventually have effect interpreters, this should all go away and become a simple switch statement that uses the functions. This will stop them from getting GCed in general. (hmm, may still need it for roc_alloc and friends)

Fix the musl build

---

src/src/lib.rs
src/src/main.rs

I am not going to pretend to fully comprehend what is going on, but this seems to fix the segfault. There is a chance the segfault is really just a strange surgical linker bug. There is also a chance of some other form of bugged cffi or memory freeing related to roc allocations.
This at least fixes locally for me and hopefully will fix in ci so we can at least cut a release. I think this is a case of small changes revealing/hiding a larger bug that is hard to track down.

I think this fixes the segfault from #123

---

src/Tcp.roc

`Tcp.withConnect` now returns the result from the callback. This is useful if you are connecting in a task that's not the outermost one (main) and you need to return a value from it.

Tcp: Return result from `Tcp.withConnect`'s callback

---

platform/Cargo.toml

I don't know if this matters at all, but I don't think we should use "rlib". The [rust docs](https://doc.rust-lang.org/reference/linkage.html) suggest using "lib" by default. "lib" probably just aliases to "rlib", but it lets the compiler pick what it wants.

Stop using "rlib"

---

platform/Path.roc

Needed to get tests passing in https://github.com/roc-lang/roc/pull/6396
(Once `List` has dropped `Nat` too, this can be reverted.)

Use `|> Num.toNat` in advance of Str dropping Nat

---

platform/Arg.roc
platform/Effect.roc
platform/InternalTcp.roc
platform/Path.roc
platform/Tcp.roc
platform/Url.roc
platform/src/lib.rs

The `Num.intCast` calls can go away in the future, but they make the transition smoother because they should work with both today's version as well as a future version where `Nat` is gone!

Remove remaining `Nat` uses from basic-cli

---

platform/Task.roc

I'm not sure why these are no longer allowed. Can diagnose later, but for now I just want to unblock `Nat` removal.

Fix Task.roc

---

platform/Task.roc

Changes the docs for `Task.seq` to match the current correct name and usage. I noticed when fiddling with the tutorial that the docs seemed to have gotten out-of-sync with the implementation recently.
Hopefully the new example is correct and clear, I'm quite new to the language!

Update docs for `Task.seq`

---

platform/Path.roc

`Path.roc` was importing `Effect.Effect` but it never used it directly. The version of the compiler on `main` doesn't catch this, but the one on `new-imports` does and it makes the tests fail.

Remove unused `Effect` type import in `Path`

---

ci/expect_scripts/result.exp
examples/.gitignore
examples/result.roc
flake.lock
platform/Task.roc

[Zulip discussion](https://roc.zulipchat.com/#narrow/stream/304902-show-and-tell/topic/Initial.20Chaining.20Syntax/near/433559391)
```roc 
app ""
packages { pf: "../platform/main.roc" }
imports [pf.Stdout, pf.Task.{ Task }]
provides [main] to pf
main : Task {} I32
main =
result =
checkFile "bad"
|> Task.result!
when result is
Ok Good -> Stdout.line "GOOD"
Ok Bad -> Stdout.line "BAD"
Err IOError -> Stdout.line "IOError"
checkFile : Str -> Task [Good, Bad] [IOError]
checkFile = \str ->
if str == "good" then 
Task.ok Good 
else if str == "bad" then 
Task.ok Bad 
else 
Task.err IOError
```

Add `Task.result`

---

platform/main.roc

Also made it more explicit that it's `Stderr.line` and not `Stdout.line` at the call site

Don't print a blank line if `Exit` is given ""

---

.github/workflows/ci_nix.yml

The macos-11 github CI runner is deprecated and will soon be removed. https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

macos-11 deprecation

---

platform/Effect.roc
platform/Env.roc
platform/src/lib.rs

This will be helpful for build scripts which can use this instead of shelling out to another program like `uname`.
```roc
ARCH : [X86, X64, ARM, AARCH64, OTHER Str]
OS : [LINUX, MACOS, WINDOWS, OTHER Str]
platform : Task {arch : ARCH, os: OS} *
```
```roc 
app [main] { pf: platform "../platform/main.roc" }
import pf.Stdout
import pf.Task exposing [Task]
import pf.Env
main =
platform = Env.platform!
Stdout.line! "Running on $(Inspect.toStr platform)"
```
```sh
$ roc examples/test.roc
Running on {arch: AARCH64, os: MACOS}
```
Closes #203

Add `Env.platform` effect

---

examples/args.roc
examples/record-builder.roc
platform/Arg.roc
platform/Arg/Builder.roc
platform/Arg/Cli.roc
platform/Arg/Help.roc
platform/Arg/Opt.roc
platform/Arg/Param.roc
platform/Arg/SubCmd.roc
platform/Arg/Subcommand.roc
platform/Arg/Validate.roc

Update the Arg module to the new record builder syntax. I removed all references to the old builder syntax from `basic-cli` except for the ones in the `Task.batch` docs. It seems like that function should be removed since it only seems useful for old record builders, but that belongs in a different PR.
I copied (and adjusted) this code from Weaver, which I just released v0.3.0 for here: https://github.com/smores56/weaver/releases/tag/0.3.0

Update Arg module to new record builder syntax

---

build.roc

The glue command may fail with a somewhat cryptic error if you provide a bad path to roc, so I started the script with a roc version check

roc version check

---

crates/roc_host/src/heap.rs
crates/roc_host/src/lib.rs
examples/tcp-client.roc
platform/Effect.roc
platform/File.roc
platform/Tcp.roc

When working on basic webserver, I realized the issue here. Overwriting a pointer with `*something = ...` in rust with drop the value already stored at the pointer. In our case, this meant dropping totally random uninitialized bytes as if they were a tcp stream. By using `std::ptr::write` we avoid the drop.
Otherwise, this PR just introduces auto free to tcp streams.

Update Tcp to use a heap like File

---

platform/Arg.roc

Found this typo when learning roc and the Arg module.

fix typo in Arg.roc

---

crates/roc_host/src/glue.rs
crates/roc_host/src/lib.rs
platform/Arg/Param.roc
platform/PlatformTasks.roc
platform/Stdin.roc
platform/glue.roc

I was doing an AoC puzzle and wanted to read all the bytes from a file piped to stdin using `roc app.roc < input.txt`, however using `Stdin.bytes` is buffered to 256 bytes at a time. This effect is more suitable as it will read until `EOF`.

Add `Stdin.readtoEnd`

---

examples/file-mixed.roc
platform/File.roc
platform/Path.roc

Zulip discussion: https://roc.zulipchat.com/#narrow/channel/304641-ideas/topic/Argument.20order.20for.20basic-cli.20file.20writing.20functions/near/482887047

Reorder file write arguments

---

.gitattributes

This seems outdated. Should we delete or update it? It references `platform/src/` which no longer exists, but `crates/roc_host_src/glue.rs` was added in `0.16.0`.

Delete outdated .gitattributes file

---

crates/roc_host_bin/build.rs
rust-toolchain.toml

Also, add `rust-analyzer` component to `rust-toolchain.toml`.

rust_host_bin: pass -Wl,-headerpad,0x1000 to reserve space for the surgical linker

---

crates/roc_file/src/lib.rs

This doesn't block our upgrades, but will be needed in future for Windows support.

Make `path_from_roc_path` pub for Windows

---

flake.lock
platform/Path.roc

Path.roc had an invalid use of the `?` operator. This should be placed after the last paren on the function call, instead of before the opening paren.

Replace invalid ? operator with try

---

platform/InternalDateTime.roc

This function [was added before the snake-case-ing](https://github.com/roc-lang/basic-cli/commit/9ecad07f5e3d8c9ff724cad12bc05800a24f2437#diff-d3a826252c93e321b0995d7a420a54f7b37890c33b6c7e6e437c879e1a4039daR112), and it was always named like this. Should the formatter notice cases like this?

Snake-case-ify epoch_millis_to_datetimeHelp function name

---

examples/dir.roc

`empty-dir`, `nested-dir`, and `another-dir` are much easier to understand than `dirExampleE`, `dirExampleA`, and `dirExampleD`.
CC @lukewilliamboswell @smores56

Clarify dir names in example

---

ci/expect_scripts/path.exp
examples/path.roc

This just seems like a leftover that the formatter can't (and shouldn't) catch.
CC @lukewilliamboswell @smores56

Snake-case-ify function names in example output

---

platform/EnvDecoding.roc

It looks like the formatter missed these [when snake-case-ing](https://github.com/roc-lang/basic-cli/commit/349a4993b25b256dc0a7224168095b78a8ef4efa#diff-58bd4936b20e4a6ea65ebe5321ce8b57c8c9972e87bb703b1be0724a2947e802R100-R107) and [when `|args|`-ing](https://github.com/roc-lang/basic-cli/pull/314).
CC @lukewilliamboswell @smores56

Snake-case-ify ignored function parameters

---

crates/roc_host/src/lib.rs
crates/roc_http/src/lib.rs

Using UTF-8 strings for the request bodies is probably a remnant from times past. The bodies are raw bytes on the Roc-side and here we align with that. This enables requests like file uploads etc. which aren't UTF-8 strings.

HTTP: Don't expect request bodies to be UTF-8

---

platform/Url.roc

Align with `basic-webserver`: https://github.com/roc-lang/basic-webserver/pull/115
Query parameters should generally be percent-encoded but it's not required. Google's OAuth doesn't percent-encode their redirect URIs which prompted this PR.

Url: Support URIs in query parameters

---

ci/expect_scripts/env.exp
flake.lock
flake.nix
tests/.gitignore
tests/env.roc

This will need tomorrow's nightly for the tests to pass.

test untested env functions

---

ci/expect_scripts/bytes-stdin-stdout.exp
ci/expect_scripts/command-line-args.exp
ci/expect_scripts/command.exp
ci/expect_scripts/env-var.exp
ci/expect_scripts/file-permissions.exp
ci/expect_scripts/file-read-write.exp
ci/expect_scripts/locale.exp
ci/expect_scripts/path-test.exp
ci/expect_scripts/path.exp
ci/expect_scripts/print.exp
ci/expect_scripts/shared-code.exp
ci/expect_scripts/sqlite-basic.exp
ci/expect_scripts/sqlite-everything.exp
ci/expect_scripts/tcp.exp
ci/expect_scripts/utc.exp

Note: I accidentally pushed to main earlier so the expect refactor is split up.

more expect refactoring
